# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: s-weigand/setup-conda@v1.0.5
        with:
          conda-channels: bioconda
      # Runs a single command using the runners shell
      - name: Install dependencies
      - run: conda install biopython
      - run: conda install pp
      - run: conda install hmmer
      - run: conda install blastpython setup.py install

      # Runs a set of commands using the runners shell
      - name: Install TEsorter
      - run: cd TEsorter
      - run: python setup.py install
      - run: TEsorter-test
